name: fastai
channels:
  - fastchan
  - conda-forge
  - defaults
dependencies:
  - python>=3
  - ipycanvas=0.12.0
  - fastai
  - black
  - ipywidgets
  - jupyterlab
  - jupyterlab_widgets
  - jupytext
  - nomkl
  - pip
  - pip:
    - duckduckgo_search
